### ISSUE TITLE
About 'Segmentation map'

### ISSUE THREAD

**Issue by so-sal** [mpizurica/WSI_mut#1]
Thank you for the great research and material.

When I read the png file, I was able to obtain a gray-scale 2dim matrix consisting of integer values between 0 and 9.
However, according to the description in the ReadMe, it is said to provide RGB channels.
I read the data as an np array after reading it in the form of a PIL Image. Did I miss anything?

mapping = {'(157, 13, 45)':'GS4+4', '(156, 1, 115)':'GS4+5',
    '(119, 95, 233)':'Tumor', '(64, 197, 186)':'GS3+5',
    '(36, 95, 137)':'GS5+5', '(157, 200, 2)':'GS4+3',
    '(64, 79, 16)':'GS3+3','(64, 128, 142)':'GS3+4',
    '(37, 38, 23)':'GS5+3','(36, 26, 93)':'GS5+4'}

**Comment by mpizurica** [comment]
Hi, sorry for the late reply - I did not see your question! I double checked with the masks_TCGA.zip file that is uploaded and I don't seem to have the issues you have. You should be able to get the RGB channels if you open the images like this:

```im = Image.open('./masks_TCGA/TCGA-2A-A8VL-01Z-00-DX1.2C2BD6EF-EC17-4117-AE89-A22B67AFB233-labels.png')```
```rgb_im = np.asarray(im.convert('RGB'))```

then, ```np.unique(rgb_im.reshape(-1, rgb_im.shape[2]), axis=0)``` should give you the following:

 array([[  0,   0,   0],
       [ 64,  79,  16],
       [ 64, 128, 142],
       [157, 200,   2]], dtype=uint8)

so the ```rgb_im``` array now contains pixels in RGB format that you can map to the gleason grades by using the mapping dict.

Hope this helps!

Best,
Marija
