### ISSUE TITLE
Annotated color (42, 31, 254) not in the annotated label map dictionary for tumors 

### ISSUE THREAD

**Issue by adiv5** [mpizurica/WSI_mut#2]
Hi,
While utilizing the masks provided in "masks_TCGA.zip" for creating the folder structure, found out that for mask with name as "TCGA-EJ-5514-01Z-00-DX1.82b0677b-fb3c-45ec-82ca-d90000d8aaf2-labels" has color (42,31,254) as the dominant color. However there is no such color in the mapping dictionary you guys provided. i.e 
```
mapping = {'(157, 13, 45)':'GS4+4', '(156, 1, 115)':'GS4+5', \
          '(119, 95, 233)':'Tumor', '(64, 197, 186)':'GS3+5', \
          '(36, 95, 137)':'GS5+5', '(157, 200, 2)':'GS4+3', \
          '(64, 79, 16)':'GS3+3','(64, 128, 142)':'GS3+4', \
          '(37, 38, 23)':'GS5+3','(36, 26, 93)':'GS5+4'}
```

How is this supposed to be handled, should such masks be ignored or is there some category that's missing?

**Comment by mpizurica** [comment]
Hi! Apologies for this oversight. This region was labeled 'GS5+3MUCINOUSCARCINOMA'. So the Gleason grade of the region is 5+3, but the pathologist indicated this region as the rare mucinous carcinoma cancer type.

**Comment by adiv5** [comment]
So, The GS5+3MUCINOUSCARCINOMA seems to be a special case as per the pathologist right so for practical purposes  should it be considered the same as GS5+3, as per the mapping

**Comment by mpizurica** [comment]
In the paper, it was indeed considered as 5+3. But you could also decide to exclude it or to consider it as a separate class.
